package rancher

import "time"

type ServiceResponse struct {
	Type         string `json:"type"`
	ResourceType string `json:"resourceType"`
	Links        struct {
		Self string `json:"self"`
	} `json:"links"`
	Actions struct {
	} `json:"actions"`
	Data      []Service `json:"data"`

}

type Service struct {
	ID    string `json:"id"`
	Type  string `json:"type"`
	Links struct {
		Self               string `json:"self"`
		Account            string `json:"account"`
		Consumedbyservices string `json:"consumedbyservices"`
		Consumedservices   string `json:"consumedservices"`
		Instances          string `json:"instances"`
		NetworkDrivers     string `json:"networkDrivers"`
		ServiceExposeMaps  string `json:"serviceExposeMaps"`
		ServiceLogs        string `json:"serviceLogs"`
		Stack              string `json:"stack"`
		StorageDrivers     string `json:"storageDrivers"`
		ContainerStats     string `json:"containerStats"`
	} `json:"links"`
	Actions struct {
		Upgrade           string `json:"upgrade"`
		Restart           string `json:"restart"`
		Update            string `json:"update"`
		Remove            string `json:"remove"`
		Deactivate        string `json:"deactivate"`
		Removeservicelink string `json:"removeservicelink"`
		Addservicelink    string `json:"addservicelink"`
		Setservicelinks   string `json:"setservicelinks"`
	} `json:"actions"`
	BaseType               string      `json:"baseType"`
	Name                   string      `json:"name"`
	State                  string      `json:"state"`
	AccountID              string      `json:"accountId"`
	AssignServiceIPAddress bool        `json:"assignServiceIpAddress"`
	CreateIndex            int         `json:"createIndex,omitempty"`
	Created                time.Time   `json:"created"`
	CreatedTS              int64       `json:"createdTS"`
	CurrentScale           int         `json:"currentScale"`
	Description            interface{} `json:"description"`
	ExternalID             interface{} `json:"externalId"`
	Fqdn                   interface{} `json:"fqdn"`
	HealthState            string      `json:"healthState"`
	InstanceIds            []string    `json:"instanceIds"`
	Kind                   string      `json:"kind"`
	LaunchConfig           struct {
		Type                  string            `json:"type"`
		BlkioWeight           interface{}       `json:"blkioWeight"`
		CapAdd                []interface{}     `json:"capAdd"`
		CapDrop               []interface{}     `json:"capDrop"`
		CgroupParent          interface{}       `json:"cgroupParent"`
		Count                 interface{}       `json:"count"`
		CPUCount              interface{}       `json:"cpuCount"`
		CPUPercent            interface{}       `json:"cpuPercent"`
		CPUPeriod             interface{}       `json:"cpuPeriod"`
		CPUQuota              interface{}       `json:"cpuQuota"`
		CPUSet                interface{}       `json:"cpuSet"`
		CPUSetMems            interface{}       `json:"cpuSetMems"`
		CPUShares             interface{}       `json:"cpuShares"`
		DataVolumes           []string          `json:"dataVolumes"`
		DataVolumesFrom       []interface{}     `json:"dataVolumesFrom"`
		Description           interface{}       `json:"description"`
		Devices               []interface{}     `json:"devices"`
		DiskQuota             interface{}       `json:"diskQuota"`
		DNS                   []interface{}     `json:"dns"`
		DNSSearch             []interface{}     `json:"dnsSearch"`
		DomainName            interface{}       `json:"domainName"`
		HealthInterval        interface{}       `json:"healthInterval"`
		HealthRetries         interface{}       `json:"healthRetries"`
		HealthTimeout         interface{}       `json:"healthTimeout"`
		Hostname              interface{}       `json:"hostname"`
		ImageUUID             string            `json:"imageUuid"`
		InstanceTriggeredStop string            `json:"instanceTriggeredStop"`
		IoMaximumBandwidth    interface{}       `json:"ioMaximumBandwidth"`
		IoMaximumIOps         interface{}       `json:"ioMaximumIOps"`
		IP                    interface{}       `json:"ip"`
		IP6                   interface{}       `json:"ip6"`
		IpcMode               interface{}       `json:"ipcMode"`
		Isolation             interface{}       `json:"isolation"`
		KernelMemory          interface{}       `json:"kernelMemory"`
		Kind                  string            `json:"kind"`
		Labels                map[string]string `json:"labels"`
		LogConfig             struct {
			Type   string `json:"type"`
			Config struct {
			} `json:"config"`
			Driver interface{} `json:"driver"`
		} `json:"logConfig"`
		Memory                       interface{}   `json:"memory"`
		MemoryMb                     interface{}   `json:"memoryMb"`
		MemoryReservation            interface{}   `json:"memoryReservation"`
		MemorySwap                   interface{}   `json:"memorySwap"`
		MemorySwappiness             interface{}   `json:"memorySwappiness"`
		MilliCPUReservation          interface{}   `json:"milliCpuReservation"`
		NetworkMode                  string        `json:"networkMode"`
		OomScoreAdj                  interface{}   `json:"oomScoreAdj"`
		PidMode                      interface{}   `json:"pidMode"`
		PidsLimit                    interface{}   `json:"pidsLimit"`
		Ports                        []interface{} `json:"ports"`
		Privileged                   bool          `json:"privileged"`
		PublishAllPorts              bool          `json:"publishAllPorts"`
		ReadOnly                     bool          `json:"readOnly"`
		RequestedIPAddress           interface{}   `json:"requestedIpAddress"`
		ShmSize                      interface{}   `json:"shmSize"`
		StartOnCreate                bool          `json:"startOnCreate"`
		StdinOpen                    bool          `json:"stdinOpen"`
		StopSignal                   interface{}   `json:"stopSignal"`
		System                       bool          `json:"system"`
		Tty                          bool          `json:"tty"`
		User                         interface{}   `json:"user"`
		Userdata                     interface{}   `json:"userdata"`
		UsernsMode                   interface{}   `json:"usernsMode"`
		Uts                          interface{}   `json:"uts"`
		Version                      string        `json:"version"`
		VolumeDriver                 interface{}   `json:"volumeDriver"`
		WorkingDir                   interface{}   `json:"workingDir"`
		DataVolumesFromLaunchConfigs []interface{} `json:"dataVolumesFromLaunchConfigs"`
		NetworkLaunchConfig          interface{}   `json:"networkLaunchConfig"`
		Vcpu                         int           `json:"vcpu"`
	} `json:"launchConfig"`
	LbConfig struct {
		Type      string `json:"type"`
		PortRules []struct {
			Type       string `json:"type"`
			Hostname   string `json:"hostname"`
			TargetPort uint   `json:"targetPort"`
		} `json:"PortRules"`
	} `json:"lbConfig"`
	LinkedServices interface{} `json:"linkedServices"`
	Metadata       struct {
		IoRancherServiceHash string `json:"io.rancher.service.hash"`
	} `json:"metadata"`
	PublicEndpoints        interface{}   `json:"publicEndpoints"`
	Removed                interface{}   `json:"removed"`
	RetainIP               interface{}   `json:"retainIp"`
	Scale                  int           `json:"scale"`
	ScalePolicy            interface{}   `json:"scalePolicy"`
	SecondaryLaunchConfigs []interface{} `json:"secondaryLaunchConfigs"`
	SelectorContainer      interface{}   `json:"selectorContainer,omitempty"`
	SelectorLink           interface{}   `json:"selectorLink"`
	StackID                string        `json:"stackId"`
	StartOnCreate          bool          `json:"startOnCreate"`
	System                 bool          `json:"system"`
	Transitioning          string        `json:"transitioning"`
	TransitioningMessage   interface{}   `json:"transitioningMessage"`
	TransitioningProgress  interface{}   `json:"transitioningProgress"`
	Upgrade                struct {
		Type              string `json:"type"`
		InServiceStrategy struct {
			Type           string `json:"type"`
			BatchSize      int    `json:"batchSize"`
			IntervalMillis int    `json:"intervalMillis"`
			LaunchConfig   struct {
				Type                  string        `json:"type"`
				BlkioWeight           interface{}   `json:"blkioWeight"`
				CapAdd                []interface{} `json:"capAdd"`
				CapDrop               []interface{} `json:"capDrop"`
				CgroupParent          interface{}   `json:"cgroupParent"`
				Count                 interface{}   `json:"count"`
				CPUCount              interface{}   `json:"cpuCount"`
				CPUPercent            interface{}   `json:"cpuPercent"`
				CPUPeriod             interface{}   `json:"cpuPeriod"`
				CPUQuota              interface{}   `json:"cpuQuota"`
				CPUSet                interface{}   `json:"cpuSet"`
				CPUSetMems            interface{}   `json:"cpuSetMems"`
				CPUShares             interface{}   `json:"cpuShares"`
				DataVolumes           []string      `json:"dataVolumes"`
				DataVolumesFrom       []interface{} `json:"dataVolumesFrom"`
				Description           interface{}   `json:"description"`
				Devices               []interface{} `json:"devices"`
				DiskQuota             interface{}   `json:"diskQuota"`
				DNS                   []interface{} `json:"dns"`
				DNSSearch             []interface{} `json:"dnsSearch"`
				DomainName            interface{}   `json:"domainName"`
				HealthInterval        interface{}   `json:"healthInterval"`
				HealthRetries         interface{}   `json:"healthRetries"`
				HealthTimeout         interface{}   `json:"healthTimeout"`
				Hostname              interface{}   `json:"hostname"`
				ImageUUID             string        `json:"imageUuid"`
				InstanceTriggeredStop string        `json:"instanceTriggeredStop"`
				IoMaximumBandwidth    interface{}   `json:"ioMaximumBandwidth"`
				IoMaximumIOps         interface{}   `json:"ioMaximumIOps"`
				IP                    interface{}   `json:"ip"`
				IP6                   interface{}   `json:"ip6"`
				IpcMode               interface{}   `json:"ipcMode"`
				Isolation             interface{}   `json:"isolation"`
				KernelMemory          interface{}   `json:"kernelMemory"`
				Kind                  string        `json:"kind"`
				Labels                struct {
					IoRancherContainerAgentRole   string `json:"io.rancher.container.agent.role"`
					IoRancherContainerCreateAgent string `json:"io.rancher.container.create_agent"`
					IoRancherContainerPullImage   string `json:"io.rancher.container.pull_image"`
				} `json:"labels"`
				LogConfig struct {
					Type   string `json:"type"`
					Config struct {
					} `json:"config"`
					Driver interface{} `json:"driver"`
				} `json:"logConfig"`
				Memory                       interface{}   `json:"memory"`
				MemoryMb                     interface{}   `json:"memoryMb"`
				MemoryReservation            interface{}   `json:"memoryReservation"`
				MemorySwap                   interface{}   `json:"memorySwap"`
				MemorySwappiness             interface{}   `json:"memorySwappiness"`
				MilliCPUReservation          interface{}   `json:"milliCpuReservation"`
				NetworkMode                  string        `json:"networkMode"`
				OomScoreAdj                  interface{}   `json:"oomScoreAdj"`
				PidMode                      interface{}   `json:"pidMode"`
				PidsLimit                    interface{}   `json:"pidsLimit"`
				Ports                        []interface{} `json:"ports"`
				Privileged                   bool          `json:"privileged"`
				PublishAllPorts              bool          `json:"publishAllPorts"`
				ReadOnly                     bool          `json:"readOnly"`
				RequestedIPAddress           interface{}   `json:"requestedIpAddress"`
				ShmSize                      interface{}   `json:"shmSize"`
				StartOnCreate                bool          `json:"startOnCreate"`
				StdinOpen                    bool          `json:"stdinOpen"`
				StopSignal                   interface{}   `json:"stopSignal"`
				System                       bool          `json:"system"`
				Tty                          bool          `json:"tty"`
				User                         interface{}   `json:"user"`
				Userdata                     interface{}   `json:"userdata"`
				UsernsMode                   interface{}   `json:"usernsMode"`
				Uts                          interface{}   `json:"uts"`
				Version                      string        `json:"version"`
				VolumeDriver                 interface{}   `json:"volumeDriver"`
				WorkingDir                   interface{}   `json:"workingDir"`
				DataVolumesFromLaunchConfigs []interface{} `json:"dataVolumesFromLaunchConfigs"`
				NetworkLaunchConfig          interface{}   `json:"networkLaunchConfig"`
				Vcpu                         int           `json:"vcpu"`
			} `json:"launchConfig"`
			PreviousLaunchConfig struct {
				Type                  string        `json:"type"`
				BlkioWeight           interface{}   `json:"blkioWeight"`
				CapAdd                []interface{} `json:"capAdd"`
				CapDrop               []interface{} `json:"capDrop"`
				CgroupParent          interface{}   `json:"cgroupParent"`
				Count                 interface{}   `json:"count"`
				CPUCount              interface{}   `json:"cpuCount"`
				CPUPercent            interface{}   `json:"cpuPercent"`
				CPUPeriod             interface{}   `json:"cpuPeriod"`
				CPUQuota              interface{}   `json:"cpuQuota"`
				CPUSet                interface{}   `json:"cpuSet"`
				CPUSetMems            interface{}   `json:"cpuSetMems"`
				CPUShares             interface{}   `json:"cpuShares"`
				DataVolumes           []string      `json:"dataVolumes"`
				DataVolumesFrom       []interface{} `json:"dataVolumesFrom"`
				Description           interface{}   `json:"description"`
				Devices               []interface{} `json:"devices"`
				DiskQuota             interface{}   `json:"diskQuota"`
				DNS                   []interface{} `json:"dns"`
				DNSSearch             []interface{} `json:"dnsSearch"`
				DomainName            interface{}   `json:"domainName"`
				HealthInterval        interface{}   `json:"healthInterval"`
				HealthRetries         interface{}   `json:"healthRetries"`
				HealthTimeout         interface{}   `json:"healthTimeout"`
				Hostname              interface{}   `json:"hostname"`
				ImageUUID             string        `json:"imageUuid"`
				InstanceTriggeredStop string        `json:"instanceTriggeredStop"`
				IoMaximumBandwidth    interface{}   `json:"ioMaximumBandwidth"`
				IoMaximumIOps         interface{}   `json:"ioMaximumIOps"`
				IP                    interface{}   `json:"ip"`
				IP6                   interface{}   `json:"ip6"`
				IpcMode               interface{}   `json:"ipcMode"`
				Isolation             interface{}   `json:"isolation"`
				KernelMemory          interface{}   `json:"kernelMemory"`
				Kind                  string        `json:"kind"`
				Labels                struct {
					IoRancherContainerAgentRole   string `json:"io.rancher.container.agent.role"`
					IoRancherContainerCreateAgent string `json:"io.rancher.container.create_agent"`
					IoRancherContainerPullImage   string `json:"io.rancher.container.pull_image"`
					IoRancherContainerStartOnce   string `json:"io.rancher.container.start_once"`
				} `json:"labels"`
				LogConfig struct {
					Type   string `json:"type"`
					Config struct {
					} `json:"config"`
					Driver interface{} `json:"driver"`
				} `json:"logConfig"`
				Memory                       interface{}   `json:"memory"`
				MemoryMb                     interface{}   `json:"memoryMb"`
				MemoryReservation            interface{}   `json:"memoryReservation"`
				MemorySwap                   interface{}   `json:"memorySwap"`
				MemorySwappiness             interface{}   `json:"memorySwappiness"`
				MilliCPUReservation          interface{}   `json:"milliCpuReservation"`
				NetworkMode                  string        `json:"networkMode"`
				OomScoreAdj                  interface{}   `json:"oomScoreAdj"`
				PidMode                      interface{}   `json:"pidMode"`
				PidsLimit                    interface{}   `json:"pidsLimit"`
				Ports                        []interface{} `json:"ports"`
				Privileged                   bool          `json:"privileged"`
				PublishAllPorts              bool          `json:"publishAllPorts"`
				ReadOnly                     bool          `json:"readOnly"`
				RequestedIPAddress           interface{}   `json:"requestedIpAddress"`
				ShmSize                      interface{}   `json:"shmSize"`
				StartOnCreate                bool          `json:"startOnCreate"`
				StdinOpen                    bool          `json:"stdinOpen"`
				StopSignal                   interface{}   `json:"stopSignal"`
				System                       bool          `json:"system"`
				Tty                          bool          `json:"tty"`
				User                         interface{}   `json:"user"`
				Userdata                     interface{}   `json:"userdata"`
				UsernsMode                   interface{}   `json:"usernsMode"`
				Uts                          interface{}   `json:"uts"`
				Version                      string        `json:"version"`
				VolumeDriver                 interface{}   `json:"volumeDriver"`
				WorkingDir                   interface{}   `json:"workingDir"`
				DataVolumesFromLaunchConfigs []interface{} `json:"dataVolumesFromLaunchConfigs"`
				NetworkLaunchConfig          interface{}   `json:"networkLaunchConfig"`
				Vcpu                         int           `json:"vcpu"`
			} `json:"previousLaunchConfig"`
			PreviousSecondaryLaunchConfigs []interface{} `json:"previousSecondaryLaunchConfigs"`
			SecondaryLaunchConfigs         []interface{} `json:"secondaryLaunchConfigs"`
			StartFirst                     bool          `json:"startFirst"`
		} `json:"inServiceStrategy"`
		ToServiceStrategy interface{} `json:"toServiceStrategy"`
	} `json:"upgrade"`
	UUID string      `json:"uuid"`
	Vip  interface{} `json:"vip"`
}
